// Motivational quotes for the home screen

export const MOTIVATIONAL_QUOTES = [
  "Discipline is choosing between what you want now and what you want most.",
  "The only bad workout is the one that didn't happen.",
  "Motivation gets you started. Discipline keeps you going.",
  "You don't have to be great to start, but you have to start to be great.",
  "The pain of discipline is nothing like the pain of regret.",
  "Success is the sum of small efforts repeated day in and day out.",
  "Discipline is the bridge between goals and accomplishment.",
  "The only way to do great work is to love what you do.",
  "Excellence is not a skill, it's an attitude.",
  "Champions aren't made in gyms. Champions are made from something deep inside them.",
  "The difference between the impossible and the possible lies in a person's determination.",
  "It's not about perfect. It's about effort.",
  "When you feel like quitting, think about why you started.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Discipline is the foundation upon which all success is built.",

  // 🔥 50 More Power Quotes
  "Small progress is still progress.",
  "Consistency beats motivation every time.",
  "Your future self is watching you right now.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "The body achieves what the mind believes.",
  "Strong habits create strong results.",
  "Hard work beats talent when talent doesn’t work hard.",
  "You didn’t come this far to only come this far.",
  "Train your mind to be stronger than your feelings.",
  "The struggle you feel today builds the strength you need tomorrow.",
  "No excuses. Just results.",
  "Success is earned, not given.",
  "Every day is a new chance to improve.",
  "Push yourself because no one else will do it for you.",
  "A little progress each day adds up to big results.",
  "Great things never come from comfort zones.",
  "The hardest lift is showing up.",
  "Discipline is doing it even when you don’t feel like it.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Winners focus on progress, not perfection.",
  "The work you put in today will pay off tomorrow.",
  "Dream big. Work bigger.",
  "Be stronger than your strongest excuse.",
  "Your only competition is yesterday’s version of you.",
  "Success starts with self-discipline.",
  "You don’t find willpower, you build it.",
  "Make yourself proud.",
  "The grind will be worth it.",
  "Sweat is just weakness leaving the body.",
  "Your limits are only in your mind.",
  "Do something today your future self will thank you for.",
  "One workout at a time.",
  "Focus. Commit. Grow.",
  "Results happen over time, not overnight.",
  "Work hard in silence. Let success make noise.",
  "Be addicted to bettering yourself.",
  "Your body can stand almost anything. It’s your mind you have to convince.",
  "Don’t wish for it. Work for it.",
  "Discipline is freedom.",
  "Stay consistent. Stay hungry.",
  "The difference is discipline.",
  "Your goals don’t care how you feel.",
  "Turn pain into power.",
  "The effort never lies.",
  "Strive for progress, not excuses.",
  "Every rep counts.",
  "Every day you train, you level up.",
  "Fall in love with the process.",
  "The results will come if you don’t quit.",
  "Earn your strength.",
  "You are built for hard things.",
  "Your discipline decides your destiny.",
  "The comeback is always stronger than the setback.",
  "Do it for the person you are becoming.",
  "Stay patient. Stay relentless.",
  "Your strongest muscle is your mindset.",
  "Discipline is the difference between wanting and achieving.",
  "Train like it matters.",
  "Your journey is your power.",
  "Keep showing up.",
  "Success is built in the boring days.",
  "Be consistent, not perfect.",
  "Your discipline will take you places motivation never will.",
];


export const getRandomQuote = () => {
  const randomIndex = Math.floor(Math.random() * MOTIVATIONAL_QUOTES.length);
  return MOTIVATIONAL_QUOTES[randomIndex];
};
